baseURL: "https://annsopirate.github.io/"
languageCode: "en-us"
title: "Portfolio de Anne-Sophie Hovart"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: true

  favicon: "/images/icon.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  #customMenus:
    #- name: "Blog"
      #Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/moi.png"
  name: "Anne-Sophie Hovart"
  namecolor: ffc107
  profession: "Fra√Æchement titulaire d'un Bac + 4 en UX/UI Design, en transition vers l'univers culturel et artistique"
  github: "https://github.com/annsopirate"
  #gitlab: "https://gitlab.com"
  linkedin: "https://www.linkedin.com/in/anne-sophie-hovart/"
  #twitter: "https://twitter.com/"
  #instagram: "https://instagram.com/"
  #facebook: "https://facebook.com"

  #Custom social links
  # customSocialLinks:
  #   - imageURL: "https://hugo-profile.netlify.app/images/fav.png"
  #     url: "https://gohugo.com"
  #   - fontAwesomeIconName: "fa fa-envelope"
  #     url: "https://gmail.com"
  
  # About
  disable_about: false
  descripe_l1_person: "üåà Heyyy ! Moi c‚Äôest Anne-Sophie, j‚Äôai 23 ans et je suis en train de d√©terminer mon nouveau projet professionnel dans l'univers culturel et artistique !"
  descripe_l2_person: "üå± J'ai derni√®rement obtenu mon Bac + 4 en UX/UI Design effectu√© chez MyDigitalSchool. Maintenant, je me consacre √† mon nouveau projet pro ! Je souhaite d√©couvrir les m√©tiers qui accompagnent les artistes, tels qu'agent artistique, charg√©e de diffusion ou tourneuse."
  descripe_l3_person: "üíô Deux exp√©riences m'ont donn√© envie de me rapprocher des m√©tiers qui accompagnent les artistes :"
  descripe_l4_person: "- Interview UX donn√©e √† Medallion.fm : En juin 2025, j'ai √©t√© inetrview√©e par Medallion, une application d√©di√©e aux passionn√©s de musique. √âtant une utilisatrice r√©guli√®re, j'ai pu partager un regard UX/UI critique sur leur interface et proposer des pistes d'am√©lioration. Je les ai recontact√©s en juillet 2025 apr√®s avoir recueilli d'autres retours utilisateurs ; \n- Mod√©ration d'une cha√Æne Twitch 1 √† 2 fois par semaine (+59k abonn√©s)."
  descripe_l5_person: "üåü Lors de mes √©tudes et de mes exp√©riences professionnelles et personnelles, j‚Äôai appris et exerc√© de nombreuses choses diverses et vari√©es. Elles me permettront d'√©voluer dans le secteur culturel et artistique, o√π cr√©ativit√©, compr√©hension et communication sont essentielles :"
  descripe_l6_person: "- Empathie utilisateur ; \n- Psychologie cognitive ; \n- UX Research (entretiens, observations, analyse de besoins) ; \n- R√©daction pour le web et r√©seaux sociaux ; \n- Storytelling visuel et textuel ; \n- Gestion d'identit√© et coh√©rence de marque ; \n- Maquettage et prototypage (Figma) ; \n- Photographie et retouche (mobile, hybride, Lightroom) ; \n- Vid√©o et montage (Premiere Pro) ; \n- Motion design (After Effects) ; \n- Webdesign et ergonomie ; \n- Cr√©ation de sites (WordPress, Elementor, Divi) ; \n- D√©veloppement front-end (HTML/CSS/JS)."
  descripe_l7_person: "üé® √Ä part √ßa, le dessin, la photographie, la lecture, l'√©criture, le cin√©ma et les Rubik's Cube sont mes passe-temps favoris !"
  descripe_l8_person: "Tu veux voir les projets que j'ai r√©alis√©s ? clique [ici](#projects) !"
 
  


  skills:
    - name: Figma
      percentage: false
    - name: XD
      percentage: 50
    - name: WordPress
      percentage: 70
    - name: Divi Builder
      percentage: 70
    - name: Lightroom Classic
      percentage: 70
    - name : After Effects (en cours d'acquisition)
      percentage: 40
    - name : Premiere Pro (en cours d'acquisition)
      percentage: 40
    - name : Photoshop (en cours d'acquisition)
      percentage : 30
    - name : Photographie
      percentage : 50
    - name: Markdown
      percentage: 95
    - name: HTML/CSS
      percentage: 80
    - name: SQL
      percentage: 80
    - name: Hugo
      percentage: 60
    - name: PHP
      percentage: 40
        

  # Experience
  disable_experience: true
  experience:
    - company: "Google"
    - company: "Facebook"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Mar 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Amazon"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Feb 2019
      enddate: Jan 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.

  # Education
  disable_education: false
  education:
    - degree: "MBA Expert"
      branch: "UI/UX Design (Bac + 4)"
      university: "MyDigitalSchool"
      startedyear: "sept. 2024"
      graduation: "sept. 2025"
    - degree: "Licence Professionnelle"
      branch: "Cr√©aWeb"
      university: "IUT de Lens"
      startedyear: "2022"
      graduation: "2023"
    - degree: "DUT"
      branch: "Informatique"
      university: "IUT de Lens"
      startedyear: "2020"
      graduation: "2022"
    - degree: "BAC S"
      branch: "Sp√© math√©matiques"
      university: "Lyc√©e Arthur Rimbaud"
      startedyear: "2019"
      graduation: "2020"

  # Projects
  projects:

    - name: "Photographies"
      date: "> 2024 √† maintenant"
      img: /images/photographies_anne-sophie_hovart.png
      githublink: ""
      featuredlink: /images/Photographies_Anne-Sophie_Hovart.pdf
      description: "Voici certaines photographies que j'ai r√©alis√©es et retouch√©es, et que j'aime particuli√®rement. Logiciels utilis√©s : Lightroom Classic (retouches) et Photoshop (montages)"

    - name: "D√©veloppement et mise en ligne du site de XavPC"
      date: "> Avril-Juillet 2025"
      img: /images/site_xavpc.png
      githublink: ""
      featuredlink: "https://xavpc.fr/"
      description: "Le site √©tant une vitrine qui ne n√©cessite pas de mises √† jour fr√©quentes, j'ai choisi de le d√©velopper de mani√®re statique, sans CMS ou constructeur, afin de r√©duire les co√ªts d'h√©bergement."
      
    - name: "Refonte du site de XavPC"
      date: "> Avril-Juillet 2025"
      img: /images/refonte_xavpc.png
      githublink: ""
      featuredlink: "https://www.figma.com/proto/wDp8OgnjMM8ofTUj5Xm5By/Refonte-site-et-identit%C3%A9-graphique-XavPC?page-id=47%3A27&node-id=189-1156&p=f&viewport=112%2C59%2C0.12&t=pI9qOyHpxySskajI-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=189%3A1156"
      description: "Ayant r√©alis√© mon stage chez XavPC, je me suis pench√©e sur la refonte de son identit√© graphique ainsi que sur la refonte de son site que j'avais moi-m√™me r√©alis√© lors de ma premi√®re ann√©e de DUT informatique, il y a ~4 ans."
    
    - name: "Hugo style Brutalisme"
      date: "> Janvier 2025"
      img: /images/hugo_brutalisme.png
      githublink: ""
      featuredlink: "https://www.figma.com/proto/jVMeSTpT0cTEi1m5V9TQkK/Conception-UX---Brutalisme--Memphis?page-id=0%3A1&node-id=152-68&viewport=1795%2C1567%2C0.21&t=sQxOGxjWmT0OVQf9-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=152%3A68&show-proto-sidebar=1"
      description: "Ce projet de cours, o√π il fallait transformer un site existant dans le style brutalisme (ici, le site du framework gohugo.io m'a permis d'exprimer ma cr√©ativit√© et d'apprendre √† cr√©er dans un style qui me pla√Æt tr√®s particuli√®rement."
  
    - name: "Hugo style Memphis"
      date: "> Mars 2025"
      img: /images/hugo_memphis.png
      githublink: ""
      featuredlink: "https://www.figma.com/proto/jVMeSTpT0cTEi1m5V9TQkK/Conception-UX---Brutalisme--Memphis?page-id=0%3A1&node-id=570-153&viewport=1795%2C1567%2C0.21&t=sQxOGxjWmT0OVQf9-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=570%3A153&show-proto-sidebar=1"
      description: "Lors d'un projet pour les cours, il fallait transformer un site existant dans le style Memphis. J'ai opt√© pour le site du framework gohugo.io pour cet exercice, ce qui a constitu√© un d√©fi tr√®s int√©ressant que j'ai su relever !"
  
    - name: "Refonte du site Croquante"
      date: "> F√©vrier - Juillet 2023"
      img: /images/site_croquante.png
      githublink: ""
      featuredlink: "https://xd.adobe.com/view/2a9b257a-f854-4d22-8eb1-355fa922eada-7fc8/"
      description: "Lors de mon alternance, j'ai r√©alis√© les maquettes pour le site de Croquante sous les consignes et conseils d'Anastasia Le Boucher."
    
    - name: "Student Atomicus"
      date: "> Avril 2023"
      img: /images/student_atomicus_hovart_anne-sophie_min.jpg
      featuredlink: /images/student_atomicus_hovart_anne-sophie.jpg
      description: "Pour ce projet photo, il fallait s'inspirer de la photographie surr√©aliste Dal√≠ Atomicus prie par Philippe Halsman. Cette photo a √©t√© prise et retouch√©e par moi. üèÉ‚Äç‚ôÇÔ∏è+üìë: Gwenael Mastrilli ‚Äî‚Äî üëü: Tr√©phine Le Gallic ‚Äî‚Äî üí¶: Lucas Girod-Roux"
      
    - name: "UI Challenge"
      date: "> F√©vrier 2023"
      img: /images/uichallenge.png
      githublink: ""
      featuredlink: "https://www.figma.com/file/mL4zjnQUlTchybndTvSOuZ/D%C3%A9fis?type=design&mode=design&t=bXvvvC08ss68RkEP-1"
      description: 'D√©fi 1 : √©cran de connexion - 45 minutes ‚Äî‚Äî
      D√©fi 2 : √©cran de r√©glage de temp√©rature - 1h30 ‚Äî‚Äî
      D√©fi 3 : widget de player de musique - 30 minutes ‚Äî‚Äî
      D√©fi 4 : √©cran de choix de pricing - 1h'

    - name: "Application de rencontre pour les +50 ans"
      date: "> Janvier - F√©vrier 2023"
      img: /images/maquettes_appli_rencontre.jpg
      githublink: ""
      featuredlink: "https://www.figma.com/file/65W1m0maM6vWf0ADoy7KTi/Appli-rencontre-%2B50-ans-(Copy)?type=design&mode=design&t=bXvvvC08ss68RkEP-1"
      description: "En groupe de trois, nous avons r√©alis√© les maquettes principales d'une application de rencontre pour les + de 50 ans. Nous avons d√©termin√© les leviers et l'objectif. Nous avons √©tudi√© les concurrents et avons mis en place un benchmark. Enfin, nous nous sommes pench√©es sur le parcours utilisateur pour mettre en place l'application."
  
    - name: "Maquettes du site Coatle"
      date: "> Octobre 2022"
      img: /images/coatle.png
      githublink: ""
      featuredlink: "https://www.figma.com/proto/TsEP7UFYoXR5UeP1H7zHjf/Exercice-3---Design-Web?page-id=0%3A1&node-id=7-155&starting-point-node-id=7%3A155&scaling=scale-down"
      description: "J'ai r√©alis√© la page d'accueil et la page produit d'un site fictif vendant du chocolat."
      
    - name: "Maquette d'une application de streaming musical"
      date: "> Octobre 2022"
      img: /images/musicapp.png
      githublink: ""
      featuredlink: "https://www.figma.com/proto/eMq1QyXQTC0NUFK5JuD49A/Exercice-2---Design-Web?page-id=0%3A1&node-id=1%3A2&viewport=397%2C167%2C0.04&scaling=scale-down&starting-point-node-id=1%3A2"
      description: "Ceci est la premi√®re maquette que je r√©alise avec Figma. En cliquant sur le lien, vous aurez acc√®s au prototype."

    - name: "Animation d'une image"
      date: "> Septembre 2022"
      img: /images/animation_image.jpg
      githublink: ""
      featuredlink: "https://mega.nz/file/X8MwTDyK#D2WaUJAf89PUBIz9AO5-EA666KDSy2vHkKXlqssdVt0"
      description: "Pour ce dernier projet en Motion Design, nous avons d√ª utiliser tous les outils appris lors des cours."

    - name: "Pr√©sentation d'un site web"
      date: "> Septembre 2022"
      img: /images/presentation_site_motion_design.png
      githublink: ""
      featuredlink: "https://mega.nz/file/LoUwFBoY#rn70qMoj3cD__ENj1s7cEFAmDekp69Us_kpLGzBBwH4"
      description: "Pour ce projet en Motion Design, il a fallu assembler dans une composition les captures du site web qu'on souhaitait pr√©senter, et dans une autre, int√©grer le d√©filement. Puis, r√©aliser l'animation des l√©gendes et le fond."

    - name: "Cr√©ation d'une banni√®re web"
      date: "> Septembre 2022"
      img: /images/banniere_web_anim.jpg
      githublink: ""
      featuredlink: "https://mega.nz/file/y0tFXDRR#nsmHU66O9H3t1JuXZhiNwhjwFC0n6g4ll_I01wPVlfc"
      description: "Pour ce projet, nous avons d√ª r√©aliser une banni√®re pour une entreprise de notre choix. Il a fallu d√©composer la r√©alisation en deux parties : r√©aliser d'abord le bandeau des r√©seaux sociaux puis le reste."

    - name: "Animation d'un logo"
      date: "> Septembre 2022"
      img: /images/anim_logo_iut_lens.jpg
      githublink: ""
      featuredlink: "https://mega.nz/file/qtVAxDbA#clD3AGvOMLXc7CZeSTepo7k44u-YQwPNElKoYz8h3uw"
      description: "En cours de Motion Design, nous avons d√ª animer le logo de l'IUT de Lens sur After Effects en utilisant diff√©rents outils de base pour la prise en main du logiciel."
    
    - name: "Cr√©ation d'un Burger Quiz en Typescript"
      date: "> Avril 2022"
      img: /images/burgerquiz.PNG
      githublink: ""
      description: "En √©quipe de 6, nous avons d√ª r√©aliser un site internet en Angular, reprenant le concept du Burger Quiz. Pendant deux jours, nous avons travaill√© comme si nous √©tions en entreprise, en suivant la m√©thode Agile."
      
    - name: "Portfolio"
      date: "> Novembre 2021 -  | Projet pour mes √©tudes"
      img: /images/portfo.png
      githublink: "https://github.com/annsopirate/Portfolio"
      featuredlink: "/"
      description: "Cr√©ation de mon portfolio √† l'aide du logiciel Hugo. Gr√¢ce √† ce projet, j'ai appris √† utiliser Hugo correctement et en profondeur !"

    - name: "Projet Web en 48 heures top chrono !"
      date: "> D√©cembre 2021"
      img: /images/prjtmarathon.png
      githublink: "https://github.com/annsopirate/Projet_Marathon"
      description: "Le \"Projet Marathon\" consistait en la r√©alisation d'un site de gestion de s√©ries t√©l√©vis√©es. Mes deux camarades et moi avons fait √©quipe avec 3 √©tudiants en DUT MMI. Nous avons r√©alis√© le back-end et eux le front."

    - name: "Site de l'entreprise XavPC"
      date: "> √ât√© 2021 | Projet personnel"
      img: /images/xavpc.PNG
      featuredlink: "http://xavpc.free.fr/"
      description: "Cr√©ation de la version 3 du site de l'enteprise XavPC en HTML / CSS. Pour m'entra√Æner pendant les vacances, j'ai voulu refaire enti√®rement ce site avec les connaissances acquises en premi√®re ann√©e."

    - name: "Portail national des IUT informatique"
      date: "> Novembre 2020 - Janvier 2021 | Projet pour mes √©tudes"
      img: /images/PNIUTI.PNG
      githublink: "https://github.com/annsopirate/projet_tutore_sem1"
      featuredlink: "https://blurryfoxer.github.io/accueil/accueil.html"
      description: "Nous avons d√ª, en √©quipe de trois, refaire le portail national des IUT informatique en HTML / CSS. √áa a √©t√© mon projet favori de ma premi√®re ann√©e."



  # Achievements
  disable_achievements: false
  achievements:
    - title: Projet Voltaire
      description: Obtention du certificat Voltaire avec un total de 848 points.
      img: /images/prjtvol.png
      url: https://mon.certificat-voltaire.fr/verification-certificat?code=AYVGVNV



    - title: CV
      description: Obtenez mon CV.
      img: /images/cv_francais.png
      url: /images/CV_HOVART_Anne-Sophie.pdf

  # Contact
  disable_contact: false
  contact_content: Si vous avez besoin de plus d'informations, ou si mon profil vous correspond, vous pouvez me contacter par mail ! Je me ferai un plaisir d'√©changer avec vous.
  email: "annesophie5922@gmail.com"
  
  # Footer
  socialiconfooter: true
  recentposts: false

  # Blog
  showdescription: false
  tweet: false
