baseURL: "https://annsopirate.github.io/"
languageCode: "en-us"
title: "Portfolio de Anne-Sophie Hovart"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: true

  favicon: "/images/icon.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  #customMenus:
    #- name: "Blog"
      #Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/moi.png"
  name: "Anne-Sophie Hovart"
  namecolor: ffc107
  profession: "Future √©tudiante en MBA Expert UI/UX Design et √† la recherche d'une alternance (2 sem. entreprise / 1 sem. √©cole)"
  github: "https://github.com/annsopirate"
  #gitlab: "https://gitlab.com"
  linkedin: "https://www.linkedin.com/in/anne-sophie-hovart/"
  #twitter: "https://twitter.com/"
  #instagram: "https://instagram.com/"
  #facebook: "https://facebook.com"

  #Custom social links
  # customSocialLinks:
  #   - imageURL: "https://hugo-profile.netlify.app/images/fav.png"
  #     url: "https://gohugo.com"
  #   - fontAwesomeIconName: "fa fa-envelope"
  #     url: "https://gmail.com"
  
  # About
  disable_about: false
  descripe_l1_person: "üåà Heyyy ! Moi c‚Äôest Anne-Sophie, j‚Äôai 21 ans, je suis en ce moment √† la recherche d‚Äôune alternance dans le web design, l‚ÄôUX/UI design !"
  descripe_l2_person: "üéì En septembre 2024, j'int√©grerai le MBA Expert UI/UX chez MyDigitalSchool. Auparavant, j‚Äôai valid√© (avec la mention bien) ma LP Cr√©aWeb que j‚Äôai effectu√©e √† l‚ÄôIUT de Lens. J‚Äôai derni√®rement effectu√© mon alternance durant 9 mois dans la [Croquante](https://croquante.fr/) agence de communication et cr√©atrice de site internet. Cette exp√©rience m‚Äôa permis de gagner en comp√©tence et d‚Äôenrichir mes connaissances."
  descripe_l3_person: "üíñ Lors de mes √©tudes et de mes exp√©riences professionnelle et personnelle, j‚Äôai appris et exerc√© de nombreuses choses diverses et vari√©es. Voici ce qui me pla√Æt par-dessus tout :"
  descripe_l4_person: "- l'UX/UI ; \n- Le maquettage et le prototypage (Figma) ; \n- La cr√©ation de sites (Divi Builder, WordPress) ; \n- Le r√©dactionnel (pour les r√©seaux sociaux et pour les sites internet) ; \n- Le r√©f√©rencement naturel (SEO) ; \n- La photographie (t√©l√©phone, num√©rique, hybride) ; \n- La cr√©ation de vid√©os pour des projets personnels ; \n- Le motion design (After Effects) ; \n- Le d√©veloppement front-end."
  descripe_l5_person: "üé® √Ä part √ßa, le dessin, la peinture, la photographie, la lecture et les Rubik's Cube sont mes passe-temps favoris !"
  descripe_l6_person: "üìï Ce que je lis en ce moment : Lou Sonata 2."
  descripe_l7_person: "üßä Mon Rubik's Cube favori : le Megaminx."
  descripe_l8_person: "Tu veux voir les projets que j'ai r√©alis√©s ? clique [ici](#projects) !"
 
  


  skills:
    - name: Figma
      percentage: 70
    - name: XD
      percentage: 50
    - name: WordPress
      percentage: 70
    - name: Divi Builder
      percentage: 70
    - name : After Effects (en cours d'acquisition)
      percentage: 40
    - name : Photoshop (en cours d'acquisition)
      percentage : 30
    - name : Photographie
      percentage : 50
    - name: Markdown
      percentage: 95
    - name: HTML/CSS
      percentage: 80
    - name: SQL
      percentage: 80
    - name: Hugo
      percentage: 60
    - name: PHP
      percentage: 40
        

  # Experience
  disable_experience: true
  experience:
    - company: "Google"
    - company: "Facebook"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Mar 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Amazon"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Feb 2019
      enddate: Jan 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.

  # Education
  disable_education: false
  education:
    - degree: "MBA Expert"
      branch: "UI/UX Design"
      university: "MyDigitalSchool"
      startedyear: "sept. 2024"
      graduation: "en cours"
    - degree: "Licence Professionnelle"
      branch: "Cr√©aWeb"
      university: "IUT de Lens"
      startedyear: "2022"
      graduation: "2023"
    - degree: "DUT"
      branch: "Informatique"
      university: "IUT de Lens"
      startedyear: "2020"
      graduation: "2022"
    - degree: "BAC S"
      branch: "Sp√© math√©matiques"
      university: "Lyc√©e Arthur Rimbaud"
      startedyear: "2019"
      graduation: "2020"

  # Projects
  projects:    
    - name: "Refonte du site Croquante"
      date: "> F√©vrier - Juillet 2023"
      img: /images/site_croquante.png
      githublink: ""
      featuredlink: "https://xd.adobe.com/view/2a9b257a-f854-4d22-8eb1-355fa922eada-7fc8/"
      description: "Lors de mon alternance, j'ai r√©alis√© les maquettes pour le site de Croquante sous les consignes et conseils d'Anastasia Le Boucher."
    
    - name: "Student Atomicus"
      date: "> Avril 2023"
      img: /images/student_atomicus_hovart_anne-sophie_min.jpg
      featuredlink: /images/student_atomicus_hovart_anne-sophie.jpg
      description: "Pour ce projet photo, il fallait s'inspirer de la photographie surr√©aliste Dal√≠ Atomicus prie par Philippe Halsman. Cette photo a √©t√© prise et retouch√©e par moi. üèÉ‚Äç‚ôÇÔ∏è+üìë: Gwenael Mastrilli ‚Äî‚Äî üëü: Tr√©phine Le Gallic ‚Äî‚Äî üí¶: Lucas Girod-Roux"
      
    - name: "UI Challenge"
      date: "> F√©vrier 2023"
      img: /images/uichallenge.png
      githublink: ""
      featuredlink: "https://www.figma.com/file/mL4zjnQUlTchybndTvSOuZ/D%C3%A9fis?type=design&mode=design&t=bXvvvC08ss68RkEP-1"
      description: 'D√©fi 1 : √©cran de connexion - 45 minutes ‚Äî‚Äî
      D√©fi 2 : √©cran de r√©glage de temp√©rature - 1h30 ‚Äî‚Äî
      D√©fi 3 : widget de player de musique - 30 minutes ‚Äî‚Äî
      D√©fi 4 : √©cran de choix de pricing - 1h'

    - name: "Application de rencontre pour les +50 ans"
      date: "> Janvier - F√©vrier 2023"
      img: /images/maquettes_appli_rencontre.jpg
      githublink: ""
      featuredlink: "https://www.figma.com/file/65W1m0maM6vWf0ADoy7KTi/Appli-rencontre-%2B50-ans-(Copy)?type=design&mode=design&t=bXvvvC08ss68RkEP-1"
      description: "En groupe de trois, nous avons r√©alis√© les maquettes principales d'une application de rencontre pour les + de 50 ans. Nous avons d√©termin√© les leviers et l'objectif. Nous avons √©tudi√© les concurrents et avons mis en place un benchmark. Enfin, nous nous sommes pench√©es sur le parcours utilisateur pour mettre en place l'application."
  
    - name: "Maquettes du site Coatle"
      date: "> Octobre 2022"
      img: /images/coatle.png
      githublink: ""
      featuredlink: "https://www.figma.com/proto/TsEP7UFYoXR5UeP1H7zHjf/Exercice-3---Design-Web?page-id=0%3A1&node-id=7-155&starting-point-node-id=7%3A155&scaling=scale-down"
      description: "J'ai r√©alis√© la page d'accueil et la page produit d'un site fictif vendant du chocolat."
      
    - name: "Maquette d'une application de streaming musical"
      date: "> Octobre 2022"
      img: /images/musicapp.png
      githublink: ""
      featuredlink: "https://www.figma.com/proto/eMq1QyXQTC0NUFK5JuD49A/Exercice-2---Design-Web?page-id=0%3A1&node-id=1%3A2&viewport=397%2C167%2C0.04&scaling=scale-down&starting-point-node-id=1%3A2"
      description: "Ceci est la premi√®re maquette que je r√©alise avec Figma. En cliquant sur le lien, vous aurez acc√®s au prototype."

    - name: "Animation d'une image"
      date: "> Septembre 2022"
      img: /images/animation_image.jpg
      githublink: ""
      featuredlink: "https://mega.nz/file/X8MwTDyK#D2WaUJAf89PUBIz9AO5-EA666KDSy2vHkKXlqssdVt0"
      description: "Pour ce dernier projet en Motion Design, nous avons d√ª utiliser tous les outils appris lors des cours."

    - name: "Pr√©sentation d'un site web"
      date: "> Septembre 2022"
      img: /images/presentation_site_motion_design.png
      githublink: ""
      featuredlink: "https://mega.nz/file/LoUwFBoY#rn70qMoj3cD__ENj1s7cEFAmDekp69Us_kpLGzBBwH4"
      description: "Pour ce projet en Motion Design, il a fallu assembler dans une composition les captures du site web qu'on souhaitait pr√©senter, et dans une autre, int√©grer le d√©filement. Puis, r√©aliser l'animation des l√©gendes et le fond."

    - name: "Cr√©ation d'une banni√®re web"
      date: "> Septembre 2022"
      img: /images/banniere_web_anim.jpg
      githublink: ""
      featuredlink: "https://mega.nz/file/y0tFXDRR#nsmHU66O9H3t1JuXZhiNwhjwFC0n6g4ll_I01wPVlfc"
      description: "Pour ce projet, nous avons d√ª r√©aliser une banni√®re pour une entreprise de notre choix. Il a fallu d√©composer la r√©alisation en deux parties : r√©aliser d'abord le bandeau des r√©seaux sociaux puis le reste."

    - name: "Animation d'un logo"
      date: "> Septembre 2022"
      img: /images/anim_logo_iut_lens.jpg
      githublink: ""
      featuredlink: "https://mega.nz/file/qtVAxDbA#clD3AGvOMLXc7CZeSTepo7k44u-YQwPNElKoYz8h3uw"
      description: "En cours de Motion Design, nous avons d√ª animer le logo de l'IUT de Lens sur After Effects en utilisant diff√©rents outils de base pour la prise en main du logiciel."
    
    - name: "Cr√©ation d'un Burger Quiz en Typescript"
      date: "> Avril 2022"
      img: /images/burgerquiz.PNG
      githublink: ""
      description: "En √©quipe de 6, nous avons d√ª r√©aliser un site internet en Angular, reprenant le concept du Burger Quiz. Pendant deux jours, nous avons travaill√© comme si nous √©tions en entreprise, en suivant la m√©thode Agile."
      
    - name: "Portfolio"
      date: "> Novembre 2021 -  | Projet pour mes √©tudes"
      img: /images/portfo.png
      githublink: "https://github.com/annsopirate/Portfolio"
      featuredlink: "/"
      description: "Cr√©ation de mon portfolio √† l'aide du logiciel Hugo. Gr√¢ce √† ce projet, j'ai appris √† utiliser Hugo correctement et en profondeur !"

    - name: "Projet Web en 48 heures top chrono !"
      date: "> D√©cembre 2021"
      img: /images/prjtmarathon.png
      githublink: "https://github.com/annsopirate/Projet_Marathon"
      description: "Le \"Projet Marathon\" consistait en la r√©alisation d'un site de gestion de s√©ries t√©l√©vis√©es. Mes deux camarades et moi avons fait √©quipe avec 3 √©tudiants en DUT MMI. Nous avons r√©alis√© le back-end et eux le front."


    - name: "Site de l'entreprise XavPC"
      date: "> √ât√© 2021 | Projet personnel"
      img: /images/xavpc.PNG
      featuredlink: "http://xavpc.free.fr/"
      description: "Cr√©ation de la version 3 du site de l'enteprise XavPC en HTML / CSS. Pour m'entra√Æner pendant les vacances, j'ai voulu refaire enti√®rement ce site avec les connaissances acquises en premi√®re ann√©e."

    - name: "Portail national des IUT informatique"
      date: "> Novembre 2020 - Janvier 2021 | Projet pour mes √©tudes"
      img: /images/PNIUTI.PNG
      githublink: "https://github.com/annsopirate/projet_tutore_sem1"
      featuredlink: "https://blurryfoxer.github.io/accueil/accueil.html"
      description: "Nous avons d√ª, en √©quipe de trois, refaire le portail national des IUT informatique en HTML / CSS. √áa a √©t√© mon projet favori de ma premi√®re ann√©e."



  # Achievements
  disable_achievements: false
  achievements:
    - title: Projet Voltaire
      description: Obtention du certificat Voltaire avec un total de 848 points.
      img: /images/prjtvol.png
      url: https://mon.certificat-voltaire.fr/verification-certificat?code=AYVGVNV



    - title: CV
      description: Obtenez mon CV en Fran√ßais.
      img: /images/cv_francais.png
      url: /images/CV_Anne-Sophie_Hovart.pdf

  # Contact
  disable_contact: false
  contact_content: Si vous avez besoin de plus d'informations, ou si mon profil vous correspond, vous pouvez me contacter par mail ! Je me ferai un plaisir d'√©changer avec vous.
  email: "anne-sophie_hovart@ens.univ-artois.fr"
  
  # Footer
  socialiconfooter: true
  recentposts: false

  # Blog
  showdescription: false
  tweet: false
